### ISSUE TITLE
separate implementation libraries

### ISSUE THREAD

**Issue by rockxwre** [itfsw/QueryBuilder#1]
Hi,

Thank you for this great library. It provides a perfect base for creating my own jQuery QueryBuilder parser.
With that in mind, I think it would be nice to separate the SQL and MongoDB implementation code from the actual core. This makes it cleaner in my opinion.
I took the liberty to try it myself. You can see the result in:
https://github.com/IQNOMY/QueryBuilder/tree/full-to-core : fork, removed SQL and MongDB implementations.
https://github.com/IQNOMY/QueryBuilderTest : contains  shared test classes and test resources
https://github.com/IQNOMY/QueryBuilder-sql : SQL implementation
https://github.com/IQNOMY/QueryBuilder-mongodb : MongoDB  implementation

What do you think about it?

Regards,
Ramon Rockx

**Comment by rockxwre** [comment]
Hi,

The source seems to be compatible with Java 7. As long as this is the case, I think it would be nice to downgrade it from Java 8 to 7. In that case, more projects, like the one I'm working on, are able to use this library.

Regards,
Ramon Rockx

**Comment by itfsw** [comment]
Sorry for reply too late, I forget to watch this project, so did not receive the email. I begin this project is for [jQuery-QueryBuilder](https://github.com/mistic100/jQuery-QueryBuilder) just compatible to [jQuery-QueryBuilder](https://github.com/mistic100/jQuery-QueryBuilder)'s js implementation. SQL and MongoDB implementation code are all in this project. So this project may not be cleaner, Thanks for your job.
