### ISSUE TITLE
downgrade to Java 7?

### ISSUE THREAD

**Issue by rockxwre** [itfsw/QueryBuilder#2]
Hi,

The source seems to be compatible with Java 7. As long as this is the case, I think it would be nice to downgrade it from Java 8 to 7. In that case, more projects, like the one I'm working on, are able to use this library.

Regards,
Ramon Rockx

**Comment by itfsw** [comment]
Sorry for reply too late, I forget to watch this project, so did not receive the email. I have downgrade this project to Java 7.
